### ISSUE TITLE
TypeError: t.indexOf is not a function

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass#117]
I updated my hopglass-server from this commit: https://github.com/hopglass/hopglass-server/commit/71ea509f9d2c29859a1975a115c2c43f5479f3f2  to the latest commit on master and just added our config and aliases: https://github.com/hopglass/hopglass-server/compare/master...freifunk-kiel:ffki

after a restart

    service hopglass-server@default restart

now whenever I look on our map:

https://map.freifunk.in-kiel.de/test/
(the broken build is moved into a subfolder `test`)

I just get this error:

    TypeError: t.indexOf is not a function

I also tried directly https://github.com/hopglass/hopglass-server/commit/71ea509f9d2c29859a1975a115c2c43f5479f3f2 without our config added, but the same error

What could have went wrong?

**Comment by anoymouserver** [comment]
How up to date is your Hopglass? The browser log does not show a version/commit.

**Comment by rubo77** [comment]
quite old, maybe a year.

I updated the git repo now and fail to build:

```
# node_modules/.bin/grunt
Running "eslint:sources" (eslint) task


Running "eslint:grunt" (eslint) task


Running "saveRevision" task

Running "git-describe:default" (git-describe) task
Warning: Expected a function Use --force to continue.

Aborted due to warnings.

**Comment by rubo77** [comment]
build with --force works, but now I get javascript errors on the webpage:
https://map.freifunk.in-kiel.de/

    TypeError: e.bezier is not a function

**Comment by anoymouserver** [comment]
I would wild guess there are some old or missing dependencies ..?

However, you've apparently fixed it yourself, according to your map link. 🙂

**Comment by rubo77** [comment]
No, I couldn't fix it I just moved back the old build folder and moved the broken installation to a subdirectory `test/`

**Comment by rubo77** [comment]
> some old or missing dependencies

What would be the command to update all node modules?

**Comment by anoymouserver** [comment]
Would you please try again to build the app?
I've tested it locally on Debian Stretch and Buster and the CI build on Ubuntu 18.04.

However, I could not install `yarn` from the apt package sources, but had to install it as described here: https://classic.yarnpkg.com/en/docs/install/#debian-stable

`npm install` instead seems to work to, but generates some deprecation warnings.

**Comment by rubo77** [comment]
cool, this seems to work but only with `--force`

You should add these commands to the Readme:

    npm install
    node_modules/.bin/grunt --force

**Comment by rubo77** [comment]
No, it didn't work out, it is broken again after some time, maybe I still had the working app.js in cache

**Comment by anoymouserver** [comment]
I won't include it in the README since @petabyteboy decided to remove official npm support in 0cc92d3206d379dafe59920f1bac74d71754562f and even npm has this issue for you.
And recommending `--force` for an installation is not useful, as it only masks a bug which should actually be fixed. Unfortunately, as I said, I can't recreate it on any system.

Since it happens in your `git-describe` task, I will see if I can find an alternative for it.

**Comment by anoymouserver** [comment]
> 
> 
> No, it didn't work out, it is broken again after some time, maybe I still had the working app.js in cache

you current installation is missing the `config.json` 🤔

**Comment by rubo77** [comment]
Ah that was it!


maybe a javascript console log message, that the config.js is missing would be good?




> I won't include it in the README since @petabyteboy decided to remove official npm support in [0cc92d3](https://github.com/hopglass/hopglass/commit/0cc92d3206d379dafe59920f1bac74d71754562f) and even npm has this issue for you.
> And recommending `--force` for an installation is not useful, as it only masks a bug which should actually be fixed. Unfortunately, as I said, I can't recreate it on any system.
> 
> Since it happens in your `git-describe` task, I will see if I can find an alternative for it.

So how do we explain this to others then in the Readme?

yawn is installed on my system but it throws this error:

    # yarn install
    00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

where should the install directory be defined? or is it yarn build or something else, that I have to call?

**Comment by rubo77** [comment]
It worked after I used the official sources: https://classic.yarnpkg.com/en/docs/install#debian-stable and removed the misleading debian `yarn` command (which is linked in the package `cmdtest`)
